# Generated by Django 2.1 on 2018-09-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destionation',
            new_name='Destination',
        ),
    ]
