# Generated by Django 2.1 on 2018-09-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20180907_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='title',
        ),
    ]
