# Generated by Django 2.1 on 2018-09-07 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20180907_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
